# Generated by Django 5.0.4 on 2024-04-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='/', max_length=255),
            preserve_default=False,
        ),
    ]
